// Copyright (C) Parity Technologies and the various Polkadot contributors, see Contributions.md
// for a list of specific contributors.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Placeholder weights for `pallet_storage_auto_renewal`.
//!
//! TODO: replace with autogenerated weights once benchmarks are available.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_storage_auto_renewal::WeightInfo for WeightInfo<T> {
	fn enable_auto_renew() -> Weight {
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1000))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn disable_auto_renew() -> Weight {
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1000))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn process_auto_renewals(n: u32) -> Weight {
		Weight::from_parts(100_000_000, 0)
			.saturating_add(Weight::from_parts(0, 40351))
			.saturating_add(T::DbWeight::get().reads(2).saturating_mul(n as u64))
			.saturating_add(T::DbWeight::get().writes(3).saturating_mul(n as u64))
	}
}
