[package]
name = "pallet-storage-auto-renewal"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition.workspace = true
license = "Apache-2.0"
repository.workspace = true
description = "Auto-renewal companion to pallet-transaction-storage"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
scale-info = { features = ["derive"], workspace = true }
tracing = { workspace = true }
transaction-storage-primitives = { workspace = true }

pallet-transaction-storage = { workspace = true }
polkadot-sdk-frame = { workspace = true, default-features = false, features = [
	"runtime",
] }

[dev-dependencies]
pallets-common = { workspace = true }

[features]
default = ["std"]
runtime-benchmarks = [
	"pallet-transaction-storage/runtime-benchmarks",
	"pallets-common/runtime-benchmarks",
	"polkadot-sdk-frame/runtime-benchmarks",
]
std = [
	"codec/std",
	"pallet-transaction-storage/std",
	"pallets-common/std",
	"polkadot-sdk-frame/std",
	"scale-info/std",
	"tracing/std",
	"transaction-storage-primitives/std",
]
try-runtime = [
	"pallet-transaction-storage/try-runtime",
	"pallets-common/try-runtime",
	"polkadot-sdk-frame/try-runtime",
]
