// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_bulletin_transaction_storage`.
//!
//! Numbers below were copied from the bulletin-paseo runtime weight file
//! (`runtimes/bulletin-paseo/src/weights/pallet_bulletin_transaction_storage.rs`,
//! frame-omni-bencher, 2026-05-07). The `RocksDbWeight` impl substitutes
//! `T::DbWeight` with `RocksDbWeight` for the same component values so tests
//! and the default runtime impl agree.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk_frame::weights_prelude::*;
use core::marker::PhantomData;

/// Weight functions needed for pallet_bulletin_transaction_storage.
pub trait WeightInfo {
	fn store(l: u32, ) -> Weight;
	fn renew() -> Weight;
	fn force_renew() -> Weight;
	fn renew_content_hash() -> Weight;
	fn apply_block_inherents(n: u32) -> Weight;
	fn on_initialize_with_expiry(n: u32) -> Weight;
	fn authorize_account() -> Weight;
	fn refresh_account_authorization() -> Weight;
	fn authorize_preimage() -> Weight;
	fn refresh_preimage_authorization() -> Weight;
	fn remove_expired_account_authorization() -> Weight;
	fn remove_expired_preimage_authorization() -> Weight;
	fn enable_auto_renew() -> Weight;
	fn disable_auto_renew() -> Weight;
	fn validate_store(l: u32) -> Weight;
	fn validate_renew() -> Weight;
	fn add_authorizer() -> Weight;
	fn remove_authorizer() -> Weight;
	fn remove_exhausted_authorizer() -> Weight;
	fn migrate_v2_to_v3_step() -> Weight;
	fn migrate_v3_to_v4_step() -> Weight;
}

/// Weights for pallet_bulletin_transaction_storage using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `TransactionStorage::BlockTransactions` (r:1 w:1)
	/// Proof: `TransactionStorage::BlockTransactions` (`max_values`: Some(1), `max_size`: Some(44034), added: 44529, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::TransactionByContentHash` (r:0 w:1)
	/// Proof: `TransactionStorage::TransactionByContentHash` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 2097152]`.
	fn store(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `203`
		//  Estimated: `45519`
		// Minimum execution time: 15_797_000 picoseconds.
		Weight::from_parts(16_440_000, 0)
			.saturating_add(Weight::from_parts(0, 45519))
			// Standard Error: 15
			.saturating_add(Weight::from_parts(6_866, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Placeholder weight for the one-shot scheduler `renew`. Reads `Transactions`
	/// to derive the size + content hash, reads `AutoRenewals` for the conflict
	/// check, writes `AutoRenewals` for the registration. Borrows
	/// `enable_auto_renew`'s envelope — same storage operations.
	fn renew() -> Weight {
		<Self as WeightInfo>::enable_auto_renew()
	}
	/// Storage: `TransactionStorage::Transactions` (r:1 w:0)
	/// Proof: `TransactionStorage::Transactions` (`max_values`: None, `max_size`: Some(44054), added: 46529, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::BlockTransactions` (r:1 w:1)
	/// Proof: `TransactionStorage::BlockTransactions` (`max_values`: Some(1), `max_size`: Some(44034), added: 44529, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::TransactionByContentHash` (r:0 w:1)
	/// Proof: `TransactionStorage::TransactionByContentHash` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn force_renew() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `367`
		//  Estimated: `47519`
		// Minimum execution time: 26_963_000 picoseconds.
		Weight::from_parts(28_675_000, 0)
			.saturating_add(Weight::from_parts(0, 47519))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `TransactionStorage::TransactionByContentHash` (r:1 w:1)
	/// Proof: `TransactionStorage::TransactionByContentHash` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::Transactions` (r:1 w:0)
	/// Proof: `TransactionStorage::Transactions` (`max_values`: None, `max_size`: Some(44054), added: 46529, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::BlockTransactions` (r:1 w:1)
	/// Proof: `TransactionStorage::BlockTransactions` (`max_values`: Some(1), `max_size`: Some(44034), added: 44529, mode: `MaxEncodedLen`)
	fn renew_content_hash() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `412`
		//  Estimated: `47519`
		// Minimum execution time: 32_305_000 picoseconds.
		Weight::from_parts(34_128_000, 0)
			.saturating_add(Weight::from_parts(0, 47519))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `TransactionStorage::ProofChecked` (r:1 w:1)
	/// Proof: `TransactionStorage::ProofChecked` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::RetentionPeriod` (r:1 w:0)
	/// Proof: `TransactionStorage::RetentionPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::Transactions` (r:1 w:0)
	/// Proof: `TransactionStorage::Transactions` (`max_values`: None, `max_size`: Some(44054), added: 46529, mode: `MaxEncodedLen`)
	/// Storage: `System::ParentHash` (r:1 w:0)
	/// Proof: `System::ParentHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::PendingAutoRenewals` (r:1 w:1)
	/// Proof: `TransactionStorage::PendingAutoRenewals` (`max_values`: Some(1), `max_size`: Some(76802), added: 77297, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::BlockTransactions` (r:1 w:1)
	/// Proof: `TransactionStorage::BlockTransactions` (`max_values`: Some(1), `max_size`: Some(44034), added: 44529, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::PermanentStorageUsed` (r:1 w:1)
	/// Proof: `TransactionStorage::PermanentStorageUsed` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0xc20bbe95ae9a16ecbfcfef6c5ccc7871` (r:1 w:0)
	/// Proof: UNKNOWN KEY `0xc20bbe95ae9a16ecbfcfef6c5ccc7871` (r:1 w:0)
	/// Storage: `TransactionStorage::Authorizations` (r:512 w:512)
	/// Proof: `TransactionStorage::Authorizations` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::TransactionByContentHash` (r:0 w:512)
	/// Proof: `TransactionStorage::TransactionByContentHash` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 512]`.
	fn apply_block_inherents(n: u32) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `44333 + n * (242 ±0)`
		//  Estimated: `78287 + n * (2560 ±0)`
		// Minimum execution time: 70_836_000 picoseconds.
		Weight::from_parts(74_908_000, 0)
			.saturating_add(Weight::from_parts(0, 78287))
			// Standard Error: 18_089
			.saturating_add(Weight::from_parts(15_826_692, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2560).saturating_mul(n.into()))
	}
	/// Storage: UNKNOWN KEY `0x0e7b504e5df47062be129a8958a7a1274e7b9012096b41c4eb3aaf947f6ea429` (r:1 w:0)
	/// Proof: UNKNOWN KEY `0x0e7b504e5df47062be129a8958a7a1274e7b9012096b41c4eb3aaf947f6ea429` (r:1 w:0)
	/// Storage: `TransactionStorage::RetentionPeriod` (r:1 w:0)
	/// Proof: `TransactionStorage::RetentionPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::Transactions` (r:1 w:1)
	/// Proof: `TransactionStorage::Transactions` (`max_values`: None, `max_size`: Some(44054), added: 46529, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::PendingAutoRenewals` (r:1 w:1)
	/// Proof: `TransactionStorage::PendingAutoRenewals` (`max_values`: Some(1), `max_size`: Some(76802), added: 77297, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::TransactionByContentHash` (r:512 w:512)
	/// Proof: `TransactionStorage::TransactionByContentHash` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::AutoRenewals` (r:512 w:0)
	/// Proof: `TransactionStorage::AutoRenewals` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::PermanentStorageUsed` (r:1 w:1)
	/// Proof: `TransactionStorage::PermanentStorageUsed` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0xc20bbe95ae9a16ecbfcfef6c5ccc7871` (r:1 w:0)
	/// Proof: UNKNOWN KEY `0xc20bbe95ae9a16ecbfcfef6c5ccc7871` (r:1 w:0)
	/// The range of component `n` is `[0, 512]`.
	fn on_initialize_with_expiry(n: u32) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `201 + n * (234 ±0)`
		//  Estimated: `78287 + n * (2555 ±0)`
		// Minimum execution time: 7_682_000 picoseconds.
		Weight::from_parts(7_830_000, 0)
			.saturating_add(Weight::from_parts(0, 78287))
			// Standard Error: 13_093
			.saturating_add(Weight::from_parts(11_392_590, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2555).saturating_mul(n.into()))
	}
	/// Storage: `TransactionStorage::Authorizations` (r:1 w:1)
	/// Proof: `TransactionStorage::Authorizations` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn authorize_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `272`
		//  Estimated: `3550`
		// Minimum execution time: 16_813_000 picoseconds.
		Weight::from_parts(17_779_000, 0)
			.saturating_add(Weight::from_parts(0, 3550))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TransactionStorage::Authorizations` (r:1 w:1)
	/// Proof: `TransactionStorage::Authorizations` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn refresh_account_authorization() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `316`
		//  Estimated: `3550`
		// Minimum execution time: 13_483_000 picoseconds.
		Weight::from_parts(14_286_000, 0)
			.saturating_add(Weight::from_parts(0, 3550))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TransactionStorage::Authorizations` (r:1 w:1)
	/// Proof: `TransactionStorage::Authorizations` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn authorize_preimage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `272`
		//  Estimated: `3550`
		// Minimum execution time: 12_256_000 picoseconds.
		Weight::from_parts(13_053_000, 0)
			.saturating_add(Weight::from_parts(0, 3550))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TransactionStorage::Authorizations` (r:1 w:1)
	/// Proof: `TransactionStorage::Authorizations` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn refresh_preimage_authorization() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `315`
		//  Estimated: `3550`
		// Minimum execution time: 13_065_000 picoseconds.
		Weight::from_parts(13_949_000, 0)
			.saturating_add(Weight::from_parts(0, 3550))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TransactionStorage::Authorizations` (r:1 w:1)
	/// Proof: `TransactionStorage::Authorizations` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn remove_expired_account_authorization() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `316`
		//  Estimated: `3550`
		// Minimum execution time: 19_035_000 picoseconds.
		Weight::from_parts(20_127_000, 0)
			.saturating_add(Weight::from_parts(0, 3550))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TransactionStorage::Authorizations` (r:1 w:1)
	/// Proof: `TransactionStorage::Authorizations` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn remove_expired_preimage_authorization() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `315`
		//  Estimated: `3550`
		// Minimum execution time: 14_241_000 picoseconds.
		Weight::from_parts(15_130_000, 0)
			.saturating_add(Weight::from_parts(0, 3550))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TransactionStorage::AutoRenewals` (r:1 w:1)
	/// Proof: `TransactionStorage::AutoRenewals` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::TransactionByContentHash` (r:1 w:0)
	/// Proof: `TransactionStorage::TransactionByContentHash` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::Transactions` (r:1 w:0)
	/// Proof: `TransactionStorage::Transactions` (`max_values`: None, `max_size`: Some(44054), added: 46529, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::Authorizations` (r:1 w:0)
	/// Proof: `TransactionStorage::Authorizations` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn enable_auto_renew() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `525`
		//  Estimated: `47519`
		// Minimum execution time: 36_710_000 picoseconds.
		Weight::from_parts(38_719_000, 0)
			.saturating_add(Weight::from_parts(0, 47519))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TransactionStorage::AllowedAuthorizers` (r:0 w:1)
	/// Proof: `TransactionStorage::AllowedAuthorizers` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	fn add_authorizer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_914_000 picoseconds.
		Weight::from_parts(7_415_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TransactionStorage::AllowedAuthorizers` (r:0 w:1)
	/// Proof: `TransactionStorage::AllowedAuthorizers` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	fn remove_authorizer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_564_000 picoseconds.
		Weight::from_parts(7_033_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TransactionStorage::AllowedAuthorizers` (r:1 w:1)
	/// Proof: `TransactionStorage::AllowedAuthorizers` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	fn remove_exhausted_authorizer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `290`
		//  Estimated: `3530`
		// Minimum execution time: 13_425_000 picoseconds.
		Weight::from_parts(14_304_000, 0)
			.saturating_add(Weight::from_parts(0, 3530))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TransactionStorage::AutoRenewals` (r:1 w:1)
	/// Proof: `TransactionStorage::AutoRenewals` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn disable_auto_renew() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `371`
		//  Estimated: `3545`
		// Minimum execution time: 18_622_000 picoseconds.
		Weight::from_parts(19_723_000, 0)
			.saturating_add(Weight::from_parts(0, 3545))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TransactionStorage::BlockTransactions` (r:1 w:0)
	/// Proof: `TransactionStorage::BlockTransactions` (`max_values`: Some(1), `max_size`: Some(44034), added: 44529, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::PermanentStorageUsed` (r:1 w:0)
	/// Proof: `TransactionStorage::PermanentStorageUsed` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0xc20bbe95ae9a16ecbfcfef6c5ccc7871` (r:1 w:0)
	/// Proof: UNKNOWN KEY `0xc20bbe95ae9a16ecbfcfef6c5ccc7871` (r:1 w:0)
	/// Storage: `TransactionStorage::Authorizations` (r:2 w:2)
	/// Proof: `TransactionStorage::Authorizations` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 2097152]`.
	fn validate_store(l: u32) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `316`
		//  Estimated: `45519`
		// Minimum execution time: 22_277_000 picoseconds.
		Weight::from_parts(22_601_000, 0)
			.saturating_add(Weight::from_parts(0, 45519))
			// Standard Error: 13
			.saturating_add(Weight::from_parts(2_792, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `TransactionStorage::Transactions` (r:1 w:0)
	/// Proof: `TransactionStorage::Transactions` (`max_values`: None, `max_size`: Some(44054), added: 46529, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::BlockTransactions` (r:1 w:0)
	/// Proof: `TransactionStorage::BlockTransactions` (`max_values`: Some(1), `max_size`: Some(44034), added: 44529, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::PermanentStorageUsed` (r:1 w:1)
	/// Proof: `TransactionStorage::PermanentStorageUsed` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0xc20bbe95ae9a16ecbfcfef6c5ccc7871` (r:1 w:0)
	/// Proof: UNKNOWN KEY `0xc20bbe95ae9a16ecbfcfef6c5ccc7871` (r:1 w:0)
	/// Storage: `TransactionStorage::Authorizations` (r:2 w:2)
	/// Proof: `TransactionStorage::Authorizations` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn validate_renew() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `533`
		//  Estimated: `47519`
		// Minimum execution time: 44_991_000 picoseconds.
		Weight::from_parts(47_394_000, 0)
			.saturating_add(Weight::from_parts(0, 47519))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `TransactionStorage::RetentionPeriod` (r:1 w:0)
	/// Proof: `TransactionStorage::RetentionPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TransactionStorage::Transactions` (r:2 w:1)
	/// Proof: `TransactionStorage::Transactions` (`max_values`: None, `max_size`: Some(44054), added: 46529, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x0e7b504e5df47062be129a8958a7a1274e7b9012096b41c4eb3aaf947f6ea429` (r:0 w:1)
	/// Proof: UNKNOWN KEY `0x0e7b504e5df47062be129a8958a7a1274e7b9012096b41c4eb3aaf947f6ea429` (r:0 w:1)
	fn migrate_v2_to_v3_step() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `41726`
		//  Estimated: `94048`
		// Minimum execution time: 134_237_000 picoseconds.
		Weight::from_parts(140_689_000, 0)
			.saturating_add(Weight::from_parts(0, 94048))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Worst-case weight for one outer-loop iteration of the v3→v4 multi-block
	/// migration: 2 reads (iterator step + raw fetch), 1 write (re-insert) per
	/// `AutoRenewals` entry. Placeholder until benchmarked.
	fn migrate_v3_to_v4_step() -> Weight {
		Weight::from_parts(10_000_000, 1_000)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn store(l: u32, ) -> Weight {
		Weight::from_parts(16_440_000, 0)
			.saturating_add(Weight::from_parts(0, 45519))
			.saturating_add(Weight::from_parts(6_866, 0).saturating_mul(l.into()))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn renew() -> Weight {
		<Self as WeightInfo>::enable_auto_renew()
	}
	fn force_renew() -> Weight {
		Weight::from_parts(28_675_000, 0)
			.saturating_add(Weight::from_parts(0, 47519))
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn renew_content_hash() -> Weight {
		Weight::from_parts(34_128_000, 0)
			.saturating_add(Weight::from_parts(0, 47519))
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn apply_block_inherents(n: u32) -> Weight {
		Weight::from_parts(74_908_000, 0)
			.saturating_add(Weight::from_parts(0, 78287))
			.saturating_add(Weight::from_parts(15_826_692, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(8))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(4))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2560).saturating_mul(n.into()))
	}
	fn on_initialize_with_expiry(n: u32) -> Weight {
		Weight::from_parts(7_830_000, 0)
			.saturating_add(Weight::from_parts(0, 78287))
			.saturating_add(Weight::from_parts(11_392_590, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(6))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(3))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2555).saturating_mul(n.into()))
	}
	fn authorize_account() -> Weight {
		Weight::from_parts(17_779_000, 0)
			.saturating_add(Weight::from_parts(0, 3550))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn refresh_account_authorization() -> Weight {
		Weight::from_parts(14_286_000, 0)
			.saturating_add(Weight::from_parts(0, 3550))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn authorize_preimage() -> Weight {
		Weight::from_parts(13_053_000, 0)
			.saturating_add(Weight::from_parts(0, 3550))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn refresh_preimage_authorization() -> Weight {
		Weight::from_parts(13_949_000, 0)
			.saturating_add(Weight::from_parts(0, 3550))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn remove_expired_account_authorization() -> Weight {
		Weight::from_parts(20_127_000, 0)
			.saturating_add(Weight::from_parts(0, 3550))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn remove_expired_preimage_authorization() -> Weight {
		Weight::from_parts(15_130_000, 0)
			.saturating_add(Weight::from_parts(0, 3550))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn enable_auto_renew() -> Weight {
		Weight::from_parts(38_719_000, 0)
			.saturating_add(Weight::from_parts(0, 47519))
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn disable_auto_renew() -> Weight {
		Weight::from_parts(19_723_000, 0)
			.saturating_add(Weight::from_parts(0, 3545))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn add_authorizer() -> Weight {
		Weight::from_parts(7_415_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn remove_authorizer() -> Weight {
		Weight::from_parts(7_033_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn remove_exhausted_authorizer() -> Weight {
		Weight::from_parts(14_304_000, 0)
			.saturating_add(Weight::from_parts(0, 3530))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn validate_store(l: u32) -> Weight {
		Weight::from_parts(22_601_000, 0)
			.saturating_add(Weight::from_parts(0, 45519))
			.saturating_add(Weight::from_parts(2_792, 0).saturating_mul(l.into()))
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn validate_renew() -> Weight {
		Weight::from_parts(47_394_000, 0)
			.saturating_add(Weight::from_parts(0, 47519))
			.saturating_add(RocksDbWeight::get().reads(6))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	fn migrate_v2_to_v3_step() -> Weight {
		Weight::from_parts(140_689_000, 0)
			.saturating_add(Weight::from_parts(0, 94048))
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn migrate_v3_to_v4_step() -> Weight {
		Weight::from_parts(10_000_000, 1_000)
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
}
